import Navbar from '@/components/Navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='max-w-[1200px] mt-24 mb-12 mx-auto p-1 border-4 border-gray-800 bg-white rounded-lg'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
